name: Install and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd up-path-gen && cargo build --verbose
    - name: Run unit tests
      run: cd up-path-gen && cargo test --verbose
    - name: Run e2e tests
      run: cd tests && . ./simple-usages.sh
